Repository EAT-SSU/Android, pull requests merged in 2025-05, with the labels that each got.

#288 [Feat] 401 토큰 만료 감지 로직 TokenAuthenticator으로 마이그레이션
  app/src/main/java/com/eatssu/android/App.kt
  app/src/main/java/com/eatssu/android/data/RetrofitImpl.kt
  app/src/main/java/com/eatssu/android/di/NetworkModule.kt
  app/src/main/java/com/eatssu/android/di/network/TokenAuthenticator.kt
  app/src/main/java/com/eatssu/android/di/network/TokenInterceptor.kt
  app/src/main/java/com/eatssu/android/domain/model/TokenState.kt
  app/src/main/java/com/eatssu/android/domain/usecase/auth/LogoutUseCase.kt
  app/src/main/java/com/eatssu/android/presentation/base/BaseActivity.kt
  app/src/main/java/com/eatssu/android/presentation/base/TokenEventBus.kt
  app/src/main/java/com/eatssu/android/presentation/login/LoginViewModel.kt
  app/src/main/java/com/eatssu/android/presentation/main/menu/MenuFragment.kt
  app/src/main/java/com/eatssu/android/presentation/main/menu/MenuViewModel.kt
  app/src/main/res/values/strings.xml
Labels: ⭐️ refactor

#294 release: 2.1.10
  app/build.gradle.kts
Labels: 🌎 Release

#297 [Hotfix] 사진 업로드 및 포토리뷰 작성 안됨 이슈 해결
  app/src/main/java/com/eatssu/android/data/repository/ReviewRepositoryImpl.kt
  app/src/main/java/com/eatssu/android/di/network/TokenInterceptor.kt
  app/src/main/java/com/eatssu/android/domain/repository/ReviewRepository.kt
  app/src/main/java/com/eatssu/android/domain/usecase/review/GetImageUrlUseCase.kt
  app/src/main/java/com/eatssu/android/presentation/cafeteria/review/list/ReviewAdapter.kt
  app/src/main/java/com/eatssu/android/presentation/cafeteria/review/write/ImageViewModel.kt
  app/src/main/java/com/eatssu/android/presentation/cafeteria/review/write/ReviewWriteRateActivity.kt
  app/src/main/java/com/eatssu/android/presentation/cafeteria/review/write/ReviewWriteViewModel.kt
  app/src/main/res/layout/activity_review_write_rate.xml
Labels: 🪲 bug, 🔥 hotfix
