Repository EAT-SSU/Android, pull requests merged in 2025-03, with the labels that each got.

#255 [Fix] 크리스마스 로고에서 기본 로고로 이미지 변경
  .github/workflows/android.yml
  app/src/main/res/layout/activity_intro.xml
Labels: 🎨 UI

#256 [Chore] item_menu 메뉴가 2줄 이상인 경우 행간 추가
  app/src/main/res/layout/item_menu.xml
Labels: 🎨 UI, ⭐️ refactor

#265 Release/2.1.5
  .github/workflows/android.yml
  README.md
  app/build.gradle.kts
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/item_menu.xml
Labels: 🌎 Release

#264 Release 2.1.5
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/img_splash_christmas.png
  app/src/main/res/layout/activity_intro.xml
Labels: 🌎 Release

#266 [Hotfix] splash 화면이 수정 전 코드로 되어있던 것 수정
  app/src/main/res/layout/activity_intro.xml
Labels: 🔥 hotfix

#269 [chore] 크리스마스 로고를 오리지널 로고로 변경
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/img_logo1_44.png
Labels: 🎨 UI

#270 [Feat] Compose 세팅
  app/build.gradle.kts
  app/src/main/java/com/eatssu/android/presentation/ComposeExample.kt
  app/src/main/java/com/eatssu/android/presentation/compose/ui/theme/Color.kt
  app/src/main/java/com/eatssu/android/presentation/compose/ui/theme/Theme.kt
  app/src/main/java/com/eatssu/android/presentation/compose/ui/theme/Type.kt
  gradle/libs.versions.toml
Labels: ✨ feature

#267 Release/2.1.6
  app/build.gradle.kts
Labels: 🌎 Release

#278 Release 2.1.7
  app/build.gradle.kts
Labels: 🌎 Release

#248 [Chore] Change delete/modify/report modal
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/eatssu/android/presentation/common/MyReviewBottomSheetFragment.kt
  app/src/main/java/com/eatssu/android/presentation/common/OthersBottomSheetFragment.kt
  app/src/main/java/com/eatssu/android/presentation/mypage/myreview/MyReviewAdapter.kt
  app/src/main/java/com/eatssu/android/presentation/mypage/myreview/MyReviewListActivity.kt
  app/src/main/java/com/eatssu/android/presentation/mypage/myreview/MyReviewViewModel.kt
  app/src/main/java/com/eatssu/android/presentation/review/delete/DeleteViewModel.kt
  app/src/main/java/com/eatssu/android/presentation/review/delete/MyReviewDialogActivity.kt
  app/src/main/java/com/eatssu/android/presentation/review/list/ReviewActivity.kt
  app/src/main/java/com/eatssu/android/presentation/review/list/ReviewAdapter.kt
  app/src/main/java/com/eatssu/android/presentation/review/list/ReviewViewModel.kt
  app/src/main/java/com/eatssu/android/presentation/review/report/OthersReviewDialogActivity.kt
  app/src/main/res/drawable/ic_pencil.xml
  app/src/main/res/drawable/ic_remove.xml
  app/src/main/res/layout/activity_fix_menu.xml
  app/src/main/res/layout/activity_my_review_dialog.xml
  app/src/main/res/layout/fragment_bottomsheet_my_review.xml
  app/src/main/res/layout/fragment_bottomsheet_others.xml
Labels: 🎨 UI, ⭐️ refactor

#281 [Feat] splash 기존 이미지로 변경 및 스플래쉬 실행 시간 2초로 복구
  app/src/main/java/com/eatssu/android/presentation/login/IntroActivity.kt
  app/src/main/res/layout/activity_intro.xml
Labels: ✨ feature

#282 [Feat] splash 배경 색 변경
  app/src/main/res/layout/activity_intro.xml
Labels: ✨ feature
